site_name: DESI SVDA
site_url: https://data.desi.lbl.gov/public/svda
nav:
  - Home: index.md
  - About: about.md

# theme: readthedocs
# theme: mkdocs
theme: material

markdown_extensions:
  - smarty
  - sane_lists
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details

extra_javascript:
  # - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg-full.js

